# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-27 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiskInfo',
            fields=[
                ('disk_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_name', models.CharField(max_length=255, verbose_name='\u540d\u5b57')),
                ('disk_type', models.CharField(max_length=255, verbose_name='\u7c7b\u578b')),
                ('disk_size', models.CharField(max_length=255, verbose_name='\u603b\u5927\u5c0f')),
                ('disk_used', models.CharField(max_length=255, verbose_name='\u4f7f\u7528')),
                ('disk_avail', models.CharField(max_length=255, verbose_name='\u53ef\u7528')),
                ('disk_mount', models.CharField(max_length=255, verbose_name='\u6302\u8f7d\u76ee\u5f55')),
                ('disk_add_time', models.DateTimeField(auto_now_add=True, verbose_name='\u63d0\u4ea4\u65f6\u95f4')),
                ('disk_disk_time', models.CharField(blank=True, max_length=250, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('disk_back_stat', models.IntegerField(default=0, verbose_name='\u5907\u7528\u76d8\u72b6\u6001')),
                ('disk_use_stat', models.IntegerField(default=0, verbose_name='\u4f7f\u7528\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='DiskStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_stat_name', models.CharField(max_length=255, verbose_name='\u76d8\u7b26')),
                ('disk_stat', models.CharField(max_length=255, verbose_name='\u72b6\u6001')),
                ('disk_slot', models.IntegerField(verbose_name='\u7f16\u53f7')),
                ('disk_off_stat', models.IntegerField(default=0, verbose_name='\u5173\u95ed\u72b6\u6001')),
                ('disk_uuid', models.CharField(blank=True, max_length=255, verbose_name='UUID')),
            ],
        ),
        migrations.CreateModel(
            name='FileGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, verbose_name='\u7fa4\u7ec4\u540d\u79f0')),
                ('user_name', models.CharField(max_length=255, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='FileManger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_disk_type', models.CharField(max_length=255, verbose_name='\u786c\u76d8\u7c7b\u578b')),
                ('file_route', models.CharField(max_length=255, verbose_name='\u6587\u4ef6\u8def\u5f84')),
                ('file_share_name', models.CharField(max_length=255, verbose_name='\u5171\u4eab\u540d\u79f0')),
                ('file_disk_name', models.CharField(max_length=255, verbose_name='\u786c\u76d8\u540d\u79f0')),
                ('file_cold_time', models.CharField(max_length=255, verbose_name='\u51bb\u7ed3\u65f6\u95f4')),
                ('file_add_time', models.DateTimeField(auto_now_add=True, verbose_name='\u63d0\u4ea4\u65f6\u95f4')),
                ('file_time', models.CharField(max_length=255, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('file_user', models.CharField(default='--', max_length=255, verbose_name='\u7528\u6237')),
                ('file_group', models.CharField(default='--', max_length=255, verbose_name='\u7fa4\u7ec4')),
                ('file_active_stat', models.CharField(default='\u672a\u6fc0\u6d3b', max_length=255, verbose_name='\u6fc0\u6d3b\u72b6\u6001')),
                ('file_share_stat', models.CharField(default='\u672a\u5171\u4eab', max_length=255, verbose_name='\u5171\u4eab\u72b6\u6001')),
                ('file_full_route', models.CharField(default='', max_length=255, verbose_name='\u5b58\u50a8\u8def\u5f84')),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='\u7528\u6237')),
                ('groupname', models.CharField(blank=True, max_length=255, verbose_name='\u7fa4\u7ec4')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='\u6587\u4ef6\u540d\u79f0')),
                ('route', models.CharField(blank=True, max_length=255, verbose_name='\u8def\u5f84')),
                ('cold_time', models.CharField(blank=True, max_length=255, verbose_name='\u51bb\u7ed3\u65f6\u95f4')),
                ('stat', models.IntegerField(default=0, verbose_name='\u72b6\u6001')),
                ('file', models.FileField(default='', upload_to=b'', verbose_name='\u9644\u4ef6\u4e0a\u4f20')),
                ('file_full_route', models.CharField(default='', max_length=255, verbose_name='\u4f20\u8f93\u8def\u5f84')),
                ('file_add_time', models.DateTimeField(auto_now_add=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='UploadDownFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', upload_to=b'', verbose_name='\u9644\u4ef6\u4e0a\u4f20')),
            ],
        ),
    ]
