# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-23 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanger',
            name='file_add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u63d0\u4ea4\u65f6\u95f4'),
        ),
    ]
