# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-29 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskstat',
            name='disk_name',
            field=models.CharField(default='-', max_length=255, verbose_name='\u540d\u79f0'),
        ),
    ]
