# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-30 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUser',
            new_name='Group',
        ),
    ]
