# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-23 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0002_auto_20180823_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanger',
            name='file_group',
            field=models.CharField(default='--', max_length=255, verbose_name='\u7fa4\u7ec4'),
        ),
        migrations.AddField(
            model_name='filemanger',
            name='file_user',
            field=models.CharField(default='--', max_length=255, verbose_name='\u7528\u6237'),
        ),
    ]
