# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-23 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0003_auto_20180823_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, verbose_name='\u7fa4\u7ec4\u540d\u79f0')),
                ('user_name', models.CharField(max_length=255, verbose_name='\u7528\u6237')),
            ],
        ),
    ]
