# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-29 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0003_auto_20180829_1756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileGroup1',
            new_name='FileGroup',
        ),
    ]
