# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-23 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0004_filegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanger',
            name='file_active_stat',
            field=models.CharField(default='\u672a\u6fc0\u6d3b', max_length=255, verbose_name='\u6fc0\u6d3b\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='filemanger',
            name='file_share_stat',
            field=models.CharField(default='\u672a\u5171\u4eab', max_length=255, verbose_name='\u5171\u4eab\u72b6\u6001'),
        ),
    ]
