# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-24 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0005_auto_20180823_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskinfo',
            name='disk_back_stat',
            field=models.IntegerField(default=0, max_length=255, verbose_name='\u5907\u7528\u76d8\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='diskinfo',
            name='disk_use_stat',
            field=models.IntegerField(default=0, max_length=255, verbose_name='\u4f7f\u7528\u72b6\u6001'),
        ),
    ]
