# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-24 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0006_auto_20180824_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_stat_name', models.CharField(max_length=255, verbose_name='')),
                ('disk_stat', models.CharField(max_length=255, verbose_name='')),
                ('disk_slot', models.CharField(max_length=255, verbose_name='')),
                ('disk_off', models.CharField(max_length=255, verbose_name='')),
                ('disk_uuid', models.CharField(blank=True, max_length=255, verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='diskinfo',
            name='disk_back_stat',
            field=models.IntegerField(default=0, verbose_name='\u5907\u7528\u76d8\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='diskinfo',
            name='disk_mount',
            field=models.CharField(max_length=255, verbose_name='\u6302\u8f7d\u76ee\u5f55'),
        ),
        migrations.AlterField(
            model_name='diskinfo',
            name='disk_use_stat',
            field=models.IntegerField(default=0, verbose_name='\u4f7f\u7528\u72b6\u6001'),
        ),
    ]
