# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-24 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0007_auto_20180824_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diskstat',
            name='disk_off',
        ),
        migrations.AddField(
            model_name='diskstat',
            name='disk_off_stat',
            field=models.IntegerField(default=0, verbose_name='\u5173\u95ed\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='diskstat',
            name='disk_slot',
            field=models.IntegerField(verbose_name='\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='diskstat',
            name='disk_stat',
            field=models.CharField(max_length=255, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='diskstat',
            name='disk_stat_name',
            field=models.CharField(max_length=255, verbose_name='\u76d8\u7b26'),
        ),
        migrations.AlterField(
            model_name='diskstat',
            name='disk_uuid',
            field=models.CharField(blank=True, max_length=255, verbose_name='UUID'),
        ),
    ]
