# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-20 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpuStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now_time', models.CharField(max_length=255)),
                ('cpu_stat', models.CharField(max_length=255)),
            ],
        ),
    ]
