# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-03 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpuLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.CharField(max_length=255, verbose_name='\u65f6\u95f4')),
                ('one_time_stat', models.CharField(max_length=255, verbose_name='1\u5206\u949f\u72b6\u6001')),
                ('five_time_stat', models.CharField(max_length=255, verbose_name='5\u5206\u949f\u72b6\u6001')),
                ('fifteen_time_stat', models.CharField(max_length=255, verbose_name='15\u5206\u949f\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='CpuStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.CharField(max_length=255, verbose_name='\u65f6\u5019')),
                ('stat', models.CharField(max_length=255, verbose_name='\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='MemStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.CharField(max_length=255, verbose_name='\u65f6\u95f4')),
                ('stat', models.CharField(max_length=255, verbose_name='\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.CharField(max_length=255, verbose_name='\u65f6\u95f4')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('on_stat', models.CharField(max_length=255, verbose_name='\u4e0a\u4f20\u72b6\u6001')),
                ('down_stat', models.CharField(max_length=255, verbose_name='\u4e0b\u8f7d\u72b6\u6001')),
            ],
        ),
    ]
