# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-31 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpuload',
            old_name='now_time',
            new_name='add_time',
        ),
        migrations.RenameField(
            model_name='cpustat',
            old_name='now_time',
            new_name='add_time',
        ),
        migrations.RenameField(
            model_name='cpustat',
            old_name='cpu_stat',
            new_name='stat',
        ),
        migrations.RenameField(
            model_name='memstat',
            old_name='now_time',
            new_name='add_time',
        ),
        migrations.RenameField(
            model_name='memstat',
            old_name='mem_stat',
            new_name='stat',
        ),
        migrations.RenameField(
            model_name='networkstat',
            old_name='now_time',
            new_name='add_time',
        ),
        migrations.RemoveField(
            model_name='networkstat',
            name='net_stat',
        ),
        migrations.AddField(
            model_name='networkstat',
            name='down_stat',
            field=models.CharField(default='', max_length=255, verbose_name='\u4e0b\u8f7d\u72b6\u6001'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networkstat',
            name='on_stat',
            field=models.CharField(default='', max_length=255, verbose_name='\u4e0a\u4f20\u72b6\u6001'),
            preserve_default=False,
        ),
    ]
