# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-26 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpuLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now_time', models.CharField(max_length=255, verbose_name='\u65f6\u95f4')),
                ('one_time_stat', models.CharField(max_length=255, verbose_name='1\u5206\u949f\u72b6\u6001')),
                ('five_time_stat', models.CharField(max_length=255, verbose_name='5\u5206\u949f\u72b6\u6001')),
                ('fifteen_time_stat', models.CharField(max_length=255, verbose_name='15\u5206\u949f\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='MemStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now_time', models.CharField(max_length=255, verbose_name='\u65f6\u95f4')),
                ('mem_stat', models.CharField(max_length=255, verbose_name='\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now_time', models.CharField(max_length=255, verbose_name='\u65f6\u95f4')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('net_stat', models.CharField(max_length=255, verbose_name='\u72b6\u6001')),
            ],
        ),
        migrations.AlterField(
            model_name='cpustat',
            name='cpu_stat',
            field=models.CharField(max_length=255, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='cpustat',
            name='now_time',
            field=models.CharField(max_length=255, verbose_name='\u65f6\u5019'),
        ),
    ]
